ASSEMBLER_FILE_EXT = '.asm'
VM_FILE_EXT = '.vm'

LOCAL_REGISTER = 'LCL'
ARGUMENT_REGISTER = 'ARG'
THIS_REGISTER = 'THIS'
THAT_REGISTER = 'THAT'
STATIC_REGISTER = '16'
POINTER_REGISTER = '3'
TEMP_REGISTER = '5'

BRANCH_EQ = 'JEQ'
BRANCH_GT = 'JGT'
BRANCH_LT = 'JLT'
