JACK_FILE_EXT = '.jack'
VM_FILE_EXT = '.vm'
TOKENIZER_FILE_EXT = 'T.xml'
PARSER_FILE_EXT = '.xml'
DOUBLE_QUOTE = '"'
XML_LINE_TAB = '  '

WHILE_LABEL_BEGIN = 'WHILE_BEGIN'
WHILE_LABEL_END = 'WHILE_END'

IF_LABEL_BEGIN = 'IF_BEGIN'
ELSE_LABEL_BEGIN = 'ELSE_BEGIN'
IF_ELSE_LABEL_END = 'IF_ELSE_END'
